name: comiko_shared
description: Shared components for Comiko.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  json_serializable: "^0.2.3+1"
  json_annotation: 0.2.0

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.5.0
